import {
  documentDirectory,
  writeAsStringAsync,
  readAsStringAsync,
  moveAsync,
} from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import { Transaction } from '../types';
import { formatDate } from '../utils/formatDate';
import { formatCurrency } from '../utils/formatCurrency';

function csvField(val: string): string {
  return `"${val.replaceAll('"', '""')}"`;
}

// RFC 4180-compliant CSV row parser — handles quoted fields with embedded commas/newlines
function parseCSVRow(line: string): string[] {
  const cols: string[] = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') { cur += '"'; i++; }
      else inQuotes = !inQuotes;
    } else if (ch === ',' && !inQuotes) {
      cols.push(cur.trim());
      cur = '';
    } else {
      cur += ch;
    }
  }
  cols.push(cur.trim());
  return cols;
}

// ─── CSV export ───────────────────────────────────────────────────────────────

export async function exportToCSV(transactions: Transaction[], filename = 'transactions'): Promise<void> {
  const header = 'Date,Type,Category,Account,Amount,Note,Tags\n';
  const rows = transactions.map((tx) =>
    [
      csvField(formatDate(tx.date)),
      csvField(tx.type),
      csvField(tx.category),
      csvField(tx.accountId),
      tx.amount.toFixed(2),
      csvField(tx.note),
      csvField(tx.tags.join(';')),
    ].join(','),
  );
  const path = `${documentDirectory}${filename}.csv`;
  await writeAsStringAsync(path, header + rows.join('\n'));
  await Sharing.shareAsync(path, { mimeType: 'text/csv', dialogTitle: 'Export Transactions' });
}

// ─── PDF export ───────────────────────────────────────────────────────────────

export async function exportToPDF(
  transactions: Transaction[],
  monthLabel: string,
  totalIncome: number,
  totalExpenses: number,
): Promise<void> {
  const rows = transactions
    .map(
      (tx) => `<tr>
        <td>${formatDate(tx.date)}</td>
        <td>${tx.merchant}</td>
        <td>${tx.category}</td>
        <td style="color:${tx.type === 'income' ? '#2DC76D' : '#FF4B4B'};font-weight:600">
          ${tx.type === 'income' ? '+' : '-'}${formatCurrency(Math.abs(tx.amount))}
        </td>
        <td>${tx.note}</td>
      </tr>`,
    )
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/>
<style>
  body{font-family:-apple-system,Helvetica,Arial,sans-serif;padding:32px;color:#1A1A2E}
  h1{color:#7C6FFF;font-size:24px;margin-bottom:4px}
  .sub{color:#9B9BB4;font-size:14px;margin-bottom:24px}
  .summary{display:flex;gap:24px;margin-bottom:32px}
  .card{background:#F5F5FA;border-radius:12px;padding:16px 24px;flex:1}
  .card-label{font-size:12px;color:#9B9BB4;margin-bottom:4px}
  .card-value{font-size:20px;font-weight:700}
  table{width:100%;border-collapse:collapse;font-size:13px}
  th{background:#7C6FFF;color:white;padding:10px 12px;text-align:left}
  td{padding:9px 12px;border-bottom:1px solid #E8E8F0}
  .footer{margin-top:32px;font-size:11px;color:#9B9BB4;text-align:center}
</style>
</head>
<body>
  <h1>💰 FinanceFlow</h1>
  <div class="sub">Monthly Statement — ${monthLabel}</div>
  <div class="summary">
    <div class="card"><div class="card-label">Income</div>
      <div class="card-value" style="color:#2DC76D">${formatCurrency(totalIncome)}</div></div>
    <div class="card"><div class="card-label">Expenses</div>
      <div class="card-value" style="color:#FF4B4B">${formatCurrency(totalExpenses)}</div></div>
    <div class="card"><div class="card-label">Net</div>
      <div class="card-value" style="color:#7C6FFF">${formatCurrency(totalIncome - totalExpenses)}</div></div>
  </div>
  <table>
    <thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount</th><th>Note</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by FinanceFlow · ${new Date().toLocaleDateString()}</div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({ html });
  const dest = `${documentDirectory}statement-${monthLabel.replaceAll(' ', '-')}.pdf`;
  await moveAsync({ from: uri, to: dest });
  await Sharing.shareAsync(dest, { mimeType: 'application/pdf', dialogTitle: 'Export PDF Statement' });
}

// ─── JSON backup ──────────────────────────────────────────────────────────────

export async function exportAllDataJSON(data: object, filename = 'financeflow-backup'): Promise<void> {
  const path = `${documentDirectory}${filename}.json`;
  await writeAsStringAsync(path, JSON.stringify(data, null, 2));
  await Sharing.shareAsync(path, { mimeType: 'application/json', dialogTitle: 'Export Backup' });
}

// ─── CSV import (bank statement) ──────────────────────────────────────────────

export interface ImportedTransaction {
  merchant: string;
  amount: number;
  type: 'income' | 'expense';
  category: string;
  categoryId: string;
  date: string;
  note: string;
  tags: string[];
  accountId: string;
  icon: string;
  iconBg: string;
  recurring: false;
}

export async function importFromCSV(uri: string): Promise<ImportedTransaction[]> {
  const raw = await readAsStringAsync(uri);
  if (!raw) return [];
  const lines = raw.trim().split('\n');
  if (lines.length < 2) return [];
  const headers = lines[0].split(',').map((h: string) => h.trim().toLowerCase());

  return lines.slice(1).flatMap((line) => {
    if (!line.trim()) return [];
    const cols = parseCSVRow(line);
    const row: Record<string, string> = {};
    headers.forEach((h: string, i: number) => { row[h] = (cols[i] ?? '').trim(); });
    const amount = Number.parseFloat(row.amount ?? '0');
    if (Number.isNaN(amount)) return [];
    return [{
      merchant: row.description ?? row.merchant ?? 'Imported',
      amount,
      type: amount >= 0 ? 'income' : 'expense',
      category: row.category ?? 'Other',
      categoryId: (row.category ?? 'other').toLowerCase().replaceAll(/\s+/g, '_'),
      date: row.date ?? new Date().toISOString().split('T')[0],
      note: row.note ?? '',
      tags: [],
      accountId: '',
      icon: '📥',
      iconBg: '#7C6FFF',
      recurring: false as const,
    }];
  });
}
